services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - dev-db
      - frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
  dev-db:
    container_name: dev-db
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres:
    driver: local
networks:
  backend:
    driver: bridge