services:
  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    networks:
      - transcendence-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local

networks:
  transcendence-network:
    driver: bridge
